name: prompt
version: 0.1.1
author: Sean Eagan <seaneagan1@gmail.com>
description: Command-line prompting that is easy to data-drive, customize, and test.
homepage: https://github.com/seaneagan/prompt
dependencies:
  mock: '>=0.11.0 <0.12.0'
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
